from typing import Protocol

from semester_pilot.domain.entities import Assignment, Course


class CourseRepository(Protocol):
    """Persistence contract for courses."""

    def create(self, course: Course) -> Course: ...

    def get(self, course_id: int) -> Course | None: ...

    def list_active(self) -> list[Course]: ...

    def update(self, course: Course) -> Course: ...

    def archive(self, course_id: int) -> Course | None: ...


class AssignmentRepository(Protocol):
    """Persistence contract for assignments."""

    def create(self, assignment: Assignment) -> Assignment: ...

    def get(self, assignment_id: int) -> Assignment | None: ...

    def list_active(self, course_id: int | None = None) -> list[Assignment]: ...

    def update(self, assignment: Assignment) -> Assignment: ...

    def archive(self, assignment_id: int) -> Assignment | None: ...
