from typing import Protocol

from .models import Subtask


class SubtaskRepository(Protocol):
    def list_for_assignment(self, assignment_id: int) -> tuple[Subtask, ...]: ...
    def get(self, subtask_id: int) -> Subtask | None: ...
    def create(self, assignment_id: int, title: str, notes: str, estimated_minutes: int | None) -> Subtask: ...
    def update(
        self, subtask_id: int, version: int, title: str, notes: str, estimated_minutes: int | None
    ) -> Subtask: ...
    def set_completed(self, subtask_id: int, version: int, completed: bool) -> Subtask: ...
    def move(self, subtask_id: int, version: int, direction: int) -> tuple[Subtask, ...]: ...
    def delete(self, subtask_id: int, version: int) -> int: ...
